apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  labels:
    app: angular
spec:
  replicas: 4
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists 
      containers:
      - name: angular
        image: tybahmed/frontachatproject
        ports:
        - containerPort: 80
