apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  labels:
    app: angular
spec:
  replicas: 4
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular
        image: tybahmed/frontachatproject
        ports:
        - containerPort: 80